### ISSUE TITLE
What is CQSIM？

### ISSUE THREAD

**Issue by Kun0913** [NanaGlutamate/simplecq#1]
Nice code bro，but what is CQSim？Is it famous？

**Comment by Kun0913** [comment]
写个使用说明吧哥，readme不够看的

**Comment by NanaGlutamate** [comment]
true dude

**Comment by Kun0913** [comment]
The usability of this project is still terrible, bro

**Comment by NanaGlutamate** [comment]
别急，急也没用

**Comment by Kun0913** [comment]
The latest README.md is really good!!!

**Comment by NanaGlutamate** [comment]
#3
